instruments = [
    'EUR_USD',
    'EUR_GBP',
    'EUR_JPY',
    'EUR_CHF',
    'EUR_CAD',
    'EUR_AUD',
    'EUR_NZD',
    'GBP_USD',
    'USD_JPY',
    'USD_CHF',
    'USD_CAD',
    'AUD_USD',
    'NZD_USD',
    'GBP_JPY',
    'GBP_CHF',
    'GBP_CAD',
    'GBP_AUD',
    'GBP_NZD',
    'AUD_JPY',
    'CAD_CHF',
    'EUR_CHF',
    'GBP_CHF',
    'AUD_CAD',
]

module.exports = instruments;